### ISSUE TITLE
Using Google App Script

### ISSUE THREAD

**Issue by ehsanamini** [adrianbota/gdrive-appdata#5]
Hi,

Thanks for the great work. I am trying to create a folder in the Gdrive appfolder with Google App Script to store my app data files. Is it possible to achieve this with your library? If so, could you kindly provide samples and documentation. If not, can you give me some pointers as where to look?

Best

**Comment by adrianbota** [comment]
Hey, I'm not sure how to create a folder. This library only allows you to create a file in the appDataFolder and then get its contents or update it. If that's what you're looking for, let me know and I will try to guide you.
