### ISSUE TITLE
Sample project needed

### ISSUE THREAD

**Issue by lainz** [adrianbota/gdrive-appdata#6]
Hi, If you can create a sample application, a small one that saves a setting and retrieves it it would be of help to newbies in Google Drive API like me.

Basically I need to store a JSON and retrieve it, nothing more. Just using the console will be enough. I can't run your plugin, I'm not sure why when I use 'save' it doesn't works and returns Uncaught null (anonymous) @ cb=gapi.loaded_0:82.

I can run the sample script from google drive quickstart nicely, but when I try to plug your plugin it doesn't works.

https://developers.google.com/drive/v3/web/quickstart/

Just extending that sample will be enough.

Thanks.

**Comment by adrianbota** [comment]
Hi there,

Maybe the code here can inspire you: https://github.com/adrianbota/chord-snippets. 
It's a working example, although it hasn't been maintained in a while.
Give that a try.

Good luck

**Comment by lainz** [comment]
Thanks, I ran your application and is storing the data. Now I'll take a look at the sources.
I close this issue and maybe you can just change the readme with that link, so newcomers with the same questions can look quickly at it. Just a suggestion.
